version: '3'

services:
    mysql:
      container_name: mysql
      build:
        context: ./mysql
        args:
          - MYSQL_VERSION=${MYSQL_VERSION}
      environment:
        - MYSQL_DATABASE=${MYSQL_DATABASE}
        - MYSQL_USER=${MYSQL_USER}
        - MYSQL_PASSWORD=${MYSQL_PASSWORD}
        - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
        - TZ=${WORKSPACE_TIMEZONE}
      volumes:
        - ${DATA_PATH_HOST}/mysql:/var/lib/mysql
        - ${MYSQL_ENTRYPOINT_INITDB}:/docker-entrypoint-initdb.d
        - ${MYSQL_HOST_LOG_PATH}:/var/lib/mysql-logs
      ports:
        - "${MYSQL_PORT}:3306"
      restart: always
      networks:
        - web

    nginx:
      container_name: nginx
      build: 
        context: ./nginx
      environment:
        - TZ=${WORKSPACE_TIMEZONE}
      volumes:
        - ${NGINX_CONFD_PATH}:/etc/nginx/conf.d
        - ${NGINX_HOST_LOG_PATH}:/var/log/nginx
      ports:
        - "${NGINX_HOST_HTTP_PORT}:80"
        - "${NGINX_HOST_HTTPS_PORT}:443"
      restart: always
      networks:
        - web


networks:
  web:
    driver: ${NETWORKS_DRIVER}

volumes:
  mysql:
    driver: ${VOLUMES_DRIVER}